# Generated by Django 5.1.7 on 2025-03-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='phone_number',
            new_name='tel',
        ),
    ]
